"""empty message

Revision ID: eaeb70837b1b
Revises: d8cdd4e81960
Create Date: 2022-04-14 11:46:07.358489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaeb70837b1b'
down_revision = 'd8cdd4e81960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guests', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'guests')
    # ### end Alembic commands ###
