"""empty message

Revision ID: b06c9280774e
Revises: 29cd4ade67c7
Create Date: 2022-04-12 20:41:54.260524

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'b06c9280774e'
down_revision = '29cd4ade67c7'
branch_labels = None
depends_on = None


def upgrade():
    if environment == "production":
        op.execute(f"ALTER TABLE <table_name> SET SCHEMA {SCHEMA};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('kitchen', sa.Boolean(), nullable=False),
    sa.Column('pool', sa.Boolean(), nullable=False),
    sa.Column('hottub', sa.Boolean(), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('ac', sa.Boolean(), nullable=False),
    sa.Column('self_check_in', sa.Boolean(), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('first_aid', sa.Boolean(), nullable=False),
    sa.Column('first_extinguisher', sa.Boolean(), nullable=False),
    sa.Column('smoking', sa.Boolean(), nullable=False),
    sa.Column('toilet_paper', sa.Boolean(), nullable=False),
    sa.Column('soap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amenities')
    # ### end Alembic commands ###
