"""empty message

Revision ID: eaeb70837b1b
Revises: d8cdd4e81960
Create Date: 2022-04-14 11:46:07.358489

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'eaeb70837b1b'
down_revision = 'd8cdd4e81960'
branch_labels = None
depends_on = None


def upgrade():
    if environment == "production":
        op.execute(f"ALTER TABLE <table_name> SET SCHEMA {SCHEMA};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guests', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'guests')
    # ### end Alembic commands ###
